#!/bin/sh  
  
if git rev-parse --verify HEAD >/dev/null 2>&1  
then  
    against=HEAD  
else  
# Initial commit: diff against an empty tree object  
    against=$(git hash-object -t tree /dev/null)
fi  
  
# Test clang-format  
clangformatout=$(git clang-format --diff --staged -q)  
  
# Redirect output to stderr.  
exec 1>&2  
  
if [ "$clangformatout" != "" ]  
then
    echo "Format error! Run git clang-format to fix it."
    exit 1
fi